### ISSUE TITLE
Serve Github pages from "gh-pages" branch

### ISSUE THREAD

**Issue by mincong-h** [mincong-h/mincong-h.github.io#33]
## Motivation

I need get around the `jekyll-pagination-v2` limitation of GitHub pages with CI. I need this plugin to paginate Chinese articles, stored in collection `cn`.

## Tasks

- [x] Create a script to build website locally
- [x] Create branch `gh-pages` and push content of `_site` there
- [x] Enable GitHub pages on branch `gh-pages`
- [x] Tested the results in production <https://mincong.io/>
- [x] Add new rule to protect `gh-pages` branch
- [ ] Write a job to do this automatically

## References

* https://mrpowerscripts.com/github-pages-circleci-jekyll-paginate-v2/
* https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
